---
title: "CHOE.JONGWOOK-HW3"
author: "JONG-WOOK-CHOE"
output:
  pdf_document: default
  html_document: default
---
BOOK HOMEWORK

1. (a) 

   (b) 
   
   (c) 
   
   (d) 
       
2. (a) 

   (b) 
   
   (c) 
   
   (d) 
 
3. (a) 

   (b) 
   
   (c) 
   
   (d) 

4. (a) 

   (b) 
   
   (c) 
   
   (d) 
 
5. (a) 

   (b) 
   
   (c) 
   
   (d) 

6. (a) 

   (b) 
   
   (c) 
   
   (d) 

7. (a) 

   (b) 
   
   (c) 
   
   (d) 
 
8. (a) 

   (b) 
   
   (c) 
   
   (d) 
 
1. (a) 

   (b) 
   
   (c) 
   
   (d) 
 
R HOMEWORK

I

```{r, echo=FALSE}
the.data = read.csv("/Users/Bosco/Desktop/WINTER2021/STA 106/data/Cancer.csv")

group.means = by(the.data$Survival,the.data$Organ,mean)
group.nis = by(the.data$Survival,the.data$Organ,length)
MSE = anova(lm(Survival ~ Organ, data = the.data))[2,3]

give.me.power = function(ybar,ni,MSE,alpha){
a = length(ybar) # Finds a
nt = sum(ni) #Finds the overall sample size
overall.mean = sum(ni*ybar)/nt # Finds the overall mean
phi = (1/sqrt(MSE))*sqrt( sum(ni*(ybar - overall.mean)^2)/a) #Finds the books value of phi
phi.star = a *phi^2 #Finds the value of phi we will use for R
Fc = qf(1-alpha,a-1,nt-a) #The critical value of F, use in R's function
power = 1 - pf(Fc, a-1, nt-a, phi.star)# The power, calculated using a non-central F
return(power)
}

POW = give.me.power(group.means,group.nis,MSE,0.05)
cat("(a) The power of the test using the sample values assuming alpha=0.05 is", POW,"\n")

overall.mean = sum(group.means*group.nis)/sum(group.nis)
effect.size = sqrt( sum( group.nis/sum(group.nis) *(group.means -overall.mean)^2 )/MSE)
library(pwr)
pwr.results1= pwr.anova.test(k = 5, f = effect.size, sig.level = 0.05, power = 0.99)
the.n1 = ceiling(pwr.results1$n)
cat("(b) If the power to be 0.99 using alpha to be 0.01, 
    the smallest sample size need for each group is",the.n1,"\n")

pwr.results2= pwr.anova.test(k = 5, f = effect.size, sig.level = 0.01, power = 0.99)
the.n2 = ceiling(pwr.results2$n)
cat("(c) If the power to be 0.99 using alpha to be 0.05, 
    the smallest sample size need for each group is",the.n2,"\n")

cat("(d) If the Fs is very large it means that a large difference exists between the sample sets. 
    Therfore the power of a test will likely to be large.","\n")
```

II

```{r, echo=FALSE}
ci = c(0,-1,0,0,1)
give.me.CI = function(ybar,ni,ci,MSE,multiplier){
if(sum(ci) != 0 & sum(ci !=0 ) != 1){
return("Error - you did not input a valid contrast")
} else if(length(ci) != length(ni)){
return("Error - not enough contrasts given")
}
else{
estimate = sum(ybar*ci)
SE = sqrt(MSE*sum(ci^2/ni))
CI = estimate + c(-1,1)*multiplier*SE
result = c(estimate,CI)
names(result) = c("Estimate","Lower Bound","Upper Bound")
return(result)
}
}
t.a = qt(1-0.05/2,nrow(the.data) - length(unique(the.data$Organ)))
CI = give.me.CI(group.means,group.nis,ci,MSE,t.a)
cat("(a) 95% confidence interval for mu_stomach - mu_bronchus is (",CI[2],CI[3],")","\n")

cat("(b) The interval from (a) includes 0 which means that there are chance two mean being same. 
    Therefore it can not suggest that there are significant difference between group.","\n")

ci = c(0,-1/2,1,0,-1/2)
t.a = qt(1-0.05/2,nrow(the.data) - length(unique(the.data$Organ)))
CI = give.me.CI(group.means,group.nis,ci,MSE,t.a)
cat("(c) 95% confidence interval for mu_colon - (mu_stomach + mu_bronchus)/2 is (",CI[2],CI[3],")","\n")

cat("(d) The interval from (c) includes 0 which means that the average of stomach and bronchus survival 
    time can be same as colon. The results show there are no significant difference between groups")
```

III

```{r, echo=FALSE}
newdata = read.csv("/Users/Bosco/Desktop/WINTER2021/STA 106/data/Green.csv")
the.table = anova(lm(weight~group, data=newdata))
pvalue=the.table[1,5]
cat("(a) The p-value for the test of equal means is ",pvalue,". 
    If alpha is 0.10 it is bigger than p-value. 
    It means there are at least one different sample mean average in the study.","\n","\n")
group.means = by(newdata$weight,newdata$group,mean)
group.sds = by(newdata$weight,newdata$group,sd)
group.nis = by(newdata$weight,newdata$group,length)
the.summary = rbind(group.means,group.sds,group.nis)
the.summary = round(the.summary,digits = 4)
colnames(the.summary) = names(group.means)
rownames(the.summary) = c("Means","Std. Dev","Sample Size")
the.summary
cat("\n")
cat("(b) gamma_1=",the.summary[1,1]-the.summary[1,2],", gamma_2=",the.summary[1,2]-the.summary[1,3],", and gamma_3=",the.summary[1,3]-the.summary[1,1],"\n")
cat("(c) The power in this test tells the proabilibty of rejecting null hypothesis 
    that there are no difference with control and experiment groups. 
    If the power is big it means there are effect on treatment.","\n")
cat("(d) The value of 1-alpha in this test tells the proability of fail to reject null hypothesis
    when it is true. In other word it is the proability of treatment not affect on plant.","\n")

```

IV

```{r, echo=FALSE}
group.means = by(newdata$weight,newdata$group,mean)
group.nis = by(newdata$weight,newdata$group,length)
MSE = anova(lm(weight ~ group, data = newdata))[2,3]

give.me.power = function(ybar,ni,MSE,alpha){
a = length(ybar) # Finds a
nt = sum(ni) #Finds the overall sample size
overall.mean = sum(ni*ybar)/nt # Finds the overall mean
phi = (1/sqrt(MSE))*sqrt( sum(ni*(ybar - overall.mean)^2)/a) #Finds the books value of phi
phi.star = a *phi^2 #Finds the value of phi we will use for R
Fc = qf(1-alpha,a-1,nt-a) #The critical value of F, use in R's function
power = 1 - pf(Fc, a-1, nt-a, phi.star)# The power, calculated using a non-central F
return(power)
}

POW = give.me.power(group.means,group.nis,MSE,0.10)
cat("(a) The power of the test using the sample values assuming alpha=0.10 is", POW,"\n")

overall.mean = sum(group.means*group.nis)/sum(group.nis)
effect.size = sqrt( sum( group.nis/sum(group.nis) *(group.means -overall.mean)^2 )/MSE)
library(pwr)
pwr.results= pwr.anova.test(k = 3, f = effect.size, sig.level = 0.05, power = 0.99)
the.n1 = ceiling(pwr.results$n)
cat("(b) If the power to be 0.99 using alpha to be 0.05, 
    the smallest sample size need for each group is",the.n1,"\n")
cat("(c) One way to increase the power of the test is to increase alpha. 
    If aplha increases then beta decrease when power is 1-beta.")

ci = c(-1/2,-1/2,1)
t.a = qt(1-0.05/2,nrow(the.data) - length(unique(the.data$Organ)))
CI = give.me.CI(group.means,group.nis,ci,MSE,t.a)
cat("(d) 95% confidence interval for the average of means of the control and treatment 1 group
to the average of the treatment 2 is (",CI[2],CI[3],")","\n")
cat("(e) The interval from (d) does not includes 0 which means that there is a statistically significant 
    difference between the groups.")

```

## Appendix

```{r,eval=FALSE}
the.data = read.csv("/Users/Bosco/Desktop/WINTER2021/STA 106/data/Cancer.csv")

group.means = by(the.data$Survival,the.data$Organ,mean)
group.nis = by(the.data$Survival,the.data$Organ,length)
MSE = anova(lm(Survival ~ Organ, data = the.data))[2,3]

give.me.power = function(ybar,ni,MSE,alpha){
a = length(ybar) # Finds a
nt = sum(ni) #Finds the overall sample size
overall.mean = sum(ni*ybar)/nt # Finds the overall mean
phi = (1/sqrt(MSE))*sqrt( sum(ni*(ybar - overall.mean)^2)/a) #Finds the books value of phi
phi.star = a *phi^2 #Finds the value of phi we will use for R
Fc = qf(1-alpha,a-1,nt-a) #The critical value of F, use in R's function
power = 1 - pf(Fc, a-1, nt-a, phi.star)# The power, calculated using a non-central F
return(power)
}

POW = give.me.power(group.means,group.nis,MSE,0.05)
cat("(a) The power of the test using the sample values assuming alpha=0.05 is", POW,"\n")

overall.mean = sum(group.means*group.nis)/sum(group.nis)
effect.size = sqrt( sum( group.nis/sum(group.nis) *(group.means -overall.mean)^2 )/MSE)
library(pwr)
pwr.results1= pwr.anova.test(k = 5, f = effect.size, sig.level = 0.05, power = 0.99)
the.n1 = ceiling(pwr.results1$n)
cat("(b) If the power to be 0.99 using alpha to be 0.01, the smallest sample size need for each group is",the.n1,"\n")

pwr.results2= pwr.anova.test(k = 5, f = effect.size, sig.level = 0.01, power = 0.99)
the.n2 = ceiling(pwr.results2$n)
cat("(c) If the power to be 0.99 using alpha to be 0.05, the smallest sample size need for each group is",the.n2,"\n")

cat("(d) If the Fs is very large it means that a large difference exists between the sample sets. Therfore the power of a test will likely to be large.","\n")

ci = c(0,-1,0,0,1)
give.me.CI = function(ybar,ni,ci,MSE,multiplier){
if(sum(ci) != 0 & sum(ci !=0 ) != 1){
return("Error - you did not input a valid contrast")
} else if(length(ci) != length(ni)){
return("Error - not enough contrasts given")
}
else{
estimate = sum(ybar*ci)
SE = sqrt(MSE*sum(ci^2/ni))
CI = estimate + c(-1,1)*multiplier*SE
result = c(estimate,CI)
names(result) = c("Estimate","Lower Bound","Upper Bound")
return(result)
}
}
t.a = qt(1-0.05/2,nrow(the.data) - length(unique(the.data$Organ)))
CI = give.me.CI(group.means,group.nis,ci,MSE,t.a)
cat("(a) 95% confidence interval for mu_stomach - mu_bronchus is (",CI[2],CI[3],")","\n")

cat("(b) The interval from (a) includes 0 which means that there are chance two mean being same. Therefore it can not suggest that there are significant difference between group.","\n")

ci = c(0,-1/2,1,0,-1/2)
t.a = qt(1-0.05/2,nrow(the.data) - length(unique(the.data$Organ)))
CI = give.me.CI(group.means,group.nis,ci,MSE,t.a)
cat("(c) 95% confidence interval for mu_colon - (mu_stomach + mu_bronchus)/2 is (",CI[2],CI[3],")","\n")

cat("(d) The interval from (c) includes 0 which means that the average of stomach and bronchus survival time can be same as colon. The results show there are no significant difference between groups")

newdata = read.csv("/Users/Bosco/Desktop/WINTER2021/STA 106/data/Green.csv")
the.table = anova(lm(weight~group, data=newdata))
pvalue=the.table[1,5]
cat("(a) The p-value for the test of equal means is ",pvalue,". If alpha is 0.10 it is bigger than p-value. It means there are at least one different sample mean average in the study.","\n","\n")
group.means = by(newdata$weight,newdata$group,mean)
group.sds = by(newdata$weight,newdata$group,sd)
group.nis = by(newdata$weight,newdata$group,length)
the.summary = rbind(group.means,group.sds,group.nis)
the.summary = round(the.summary,digits = 4)
colnames(the.summary) = names(group.means)
rownames(the.summary) = c("Means","Std. Dev","Sample Size")
the.summary
cat("\n")
cat("(b) gamma_1=",the.summary[1,1]-the.summary[1,2],", gamma_2=",the.summary[1,2]-the.summary[1,3],", and gamma_3=",the.summary[1,3]-the.summary[1,1],"\n")
cat("(c) The power in this test tells the proabilibty of rejecting null hypothesis that there are no difference with control and experiment groups. If the power is big it means there are effect on treatment.","\n")
cat("(d) The value of 1-alpha in this test tells the proability of fail to reject null hypothesis when it is true. In other word it is the proability of treatment not affect on plant.","\n")

group.means = by(newdata$weight,newdata$group,mean)
group.nis = by(newdata$weight,newdata$group,length)
MSE = anova(lm(weight ~ group, data = newdata))[2,3]

give.me.power = function(ybar,ni,MSE,alpha){
a = length(ybar) # Finds a
nt = sum(ni) #Finds the overall sample size
overall.mean = sum(ni*ybar)/nt # Finds the overall mean
phi = (1/sqrt(MSE))*sqrt( sum(ni*(ybar - overall.mean)^2)/a) #Finds the books value of phi
phi.star = a *phi^2 #Finds the value of phi we will use for R
Fc = qf(1-alpha,a-1,nt-a) #The critical value of F, use in R's function
power = 1 - pf(Fc, a-1, nt-a, phi.star)# The power, calculated using a non-central F
return(power)
}

POW = give.me.power(group.means,group.nis,MSE,0.10)
cat("(a) The power of the test using the sample values assuming alpha=0.10 is", POW,"\n")

overall.mean = sum(group.means*group.nis)/sum(group.nis)
effect.size = sqrt( sum( group.nis/sum(group.nis) *(group.means -overall.mean)^2 )/MSE)
library(pwr)
pwr.results= pwr.anova.test(k = 3, f = effect.size, sig.level = 0.05, power = 0.99)
the.n1 = ceiling(pwr.results$n)
cat("(b) If the power to be 0.99 using alpha to be 0.05, the smallest sample size need for each group is",the.n1,"\n")
cat("(c) One way to increase the power of the test is to increase alpha. If aplha increases then beta decrease when power is 1-beta.")

ci = c(-1/2,-1/2,1)
t.a = qt(1-0.05/2,nrow(the.data) - length(unique(the.data$Organ)))
CI = give.me.CI(group.means,group.nis,ci,MSE,t.a)
cat("(d) 95% confidence interval for the average of means of the control and treatment 1 group
to the average of the treatment 2 is (",CI[2],CI[3],")","\n")
cat("(e) The interval from (d) does not includes 0 which means that there is a statistically significant difference between the groups.")
```